### ISSUE TITLE
How and in which file to implement the IndexedDBconfiguration

### ISSUE THREAD

**Issue by JEEVANJGA** [mydea/ember-indexeddb#1]
In my Ember application, there are 5 routes including the application route.
I need to store the JSON data fetched by each 4 routes upon selection to IndexedDB.
All 4 routes have similar JS file as follows:

      import Ember from 'ember';

      export default Ember.Route.extend({
	model(){
		return Ember.$.get('https://newsapi.org/v1/articles?source=bbc-news&sortBy=top&apiKey=c4ea221e6833496bad7716c6c4fc5ece');
	}
    });

I need to store the JSON data fetched while online to IndexedDB to implement the offline functionality using service worker. Service worker part is done using broccoli-serviceworker.

A detailed example of configuring the database, 
storing model data from each model and 
fetching the database stored content for each model with respect to their routes will be more helpful.

**Comment by mydea** [comment]
Hi,

not exactly sure how you'd access the indexeddb service in a service worker.
The way we are using it, is by basically having a special sync-service that has a "sync" method. This method will 

a) try to send any changed stuff to the server. We do this manually, by having a field "isSynced" on models that we manually set and then query by.
b) Load data from the API and then put it into IndexedDB. 

You could then run this method in the application-routes beforeModel() hook. So it would try to re-fetch from the API, and put it into IndexedDB, or else (if offline) use the stuff that was in IndexedDB before.

A description of how to configure the database is in the readme: https://github.com/mydea/ember-indexeddb#configuring-your-database

**Comment by JEEVANJGA** [comment]
@mydea
I would like to know where should we include the database configuration code.
it's not clearly mentioned in readme

**Comment by mydea** [comment]
Have you read through the link I provided?

Basically, create a service: `ember g service ember indexed-db-configuration`

Then, make it extend the IndexedDBConfiguration service:

```js
import IndexedDbConfigurationService from 'ember-indexeddb/services/indexed-db-configuration';

export default IndexedDbConfigurationService.extend({
  currentVersion: 1,

  version1: {
    stores: {
      'model-one': '&id,*isNew',
      'model-two': '&id,*status,*modelOne,[status+modelOne]'
    }
  }
});
```

**Comment by mydea** [comment]
I'm closing this - if there are any other questions, please feel free to re-open it.
