### ISSUE TITLE
store.query seems doesnt work

### ISSUE THREAD

**Issue by wojtasss** [mydea/ember-indexeddb#110]
store.findAll('task') works fine, but store.query('task', { kind: 'habbit' }) doesnt work, despite there are records in indexeddb and even ember inspector shows that records exists

**Comment by mydea** [comment]
Have you configured the `mapTable` accordingly? You can only filter (on DB level) for things defined there, e.g.:

```js
mapTable = {
  task: (item) => {
    return {
       id: this._toString(item.id),
       json: this._cleanupObject(item),
       // Add any other field you want to query
       kind: item.kind
     };
  }
}
```

**Comment by wojtasss** [comment]
my services/indexed-db-configuration.js

```
import IndexedDbConfigurationService from 'ember-indexeddb/services/indexed-db-configuration';

export default class IndexedDb extends IndexedDbConfigurationService {
  currentVersion = 1;

  version1 = {
    stores: {
      'task': '++id,name,kind,checked,timer,duration,repeat'
    }
  }

  mapTable = {
    task: (item) => {
      return {
        id: this._toString(item.id),
        json: this._cleanupObject(item),
        kind: item.kind
      };
    }
  }
}
```
I have a error during save record on Ember data:
`this._cleanupObject is not a function`

**Comment by wojtasss** [comment]
OK, it shoud be `this._cleanObject`, now there is no error but still `store.query('task', { kind: 'habbit' })` doesn't work despite records exists in indexeddb :(

**Comment by mydea** [comment]
So just so I understand this, this query returns an empty array?

**Comment by mydea** [comment]
You can try the new [3.0.0-beta.0](https://github.com/mydea/ember-indexeddb/releases/tag/v3.0.0-beta.0) version, and set `_shouldLogQuery = true` on the indexed-db service (extend it if you haven't yet). That should output exactly which index is used per query, maybe that helps?

**Comment by wojtasss** [comment]
Thanks for your engagement to my issue, I will try it today later and give you feedback :)

**Comment by wojtasss** [comment]
I have installed your new beta version, override `_shouldLogQuery = true` but still have problems, this is my browser console 

[screen browser console _shouldLogQuery](https://imgur.com/67fBEHq)
[screen data in browser indexeddb](https://imgur.com/Oy7TsLQ)
here is also my simple project on bitbucket, maybe I am doing something wrong?
[indexeddb-test repository](https://bitbucket.org/wojtasssss/indexeddb-test/src/master/)

**Comment by wojtasss** [comment]
OK now it works, I was trying reproduce why it was not working, and I found that here
```javascript
mapTable = {
    'book': (item) => {
      return {
        id: this._toString(item.id),
        json: this._cleanObject(item),
        name: item.name // <--------- THIS DOESN'T WORK
        name: item.attributes.name // <------------- THIS WORKS LIKE A CHARM 
      };
    }
  }
```

Thank you very much for your help ;)

**Comment by mydea** [comment]
Glad you figured it out - yeah, the mapping is a bit tricky. There might be a better (automatic?) way to handle this, but I haven't had a great idea yet...!
