### ISSUE TITLE
Incompatible with ember-cli >= v3.24

### ISSUE THREAD

**Issue by jacobq** [mydea/ember-indexeddb#161]
> Error: Could not find module `ember-test-helpers/wait` imported from `ember-indexeddb/test-support/helpers/indexed-db`

ember-test-helpers v2.0.0 drops `ember-test-helpers/wait` (and 2.x is used in [new ember apps](https://github.com/ember-cli/ember-new-output/blob/v3.26.1/package.json#L27)/addons)
[`ember-test-helpers` changelog](https://github.com/emberjs/ember-test-helpers/blob/master/CHANGELOG.md#v200-2020-10-20) ([corresponding PR](https://github.com/emberjs/ember-test-helpers/pull/818))

https://github.com/mydea/ember-indexeddb/blob/6b9ac36a68bef13d92d5c5a30e7b92d09b2e1ffe/addon-test-support/helpers/indexed-db.js#L3

**Comment by mydea** [comment]
This is released as 3.0.0-beta.1 - let me know if you encounter any issues!
