### ISSUE TITLE
Data not really stored in the store

### ISSUE THREAD

**Issue by randy-argonillo** [mydea/ember-indexeddb#5]
https://github.com/mydea/ember-indexeddb/blob/b2a4601907d7d1b64d86951ab4ed85a8ee760600/addon/adapters/indexed-db.js#L75

Hi,

Just want to clarify my understanding with regards to the behaviour of the code and the propagation of changes to templates. I'm seeing here that adapter just gets the data from IndexedDB. However, I don't see here that we are putting the return data to Ember Store. If ever there are changes on the data will this get propagated to all templates? I know this type of change is supposedly handled already by Ember Data where one change can be seen across multiple views.

**Comment by mydea** [comment]
Putting the returned data into the store is not the concern of the adapter - this is handled by Ember Data itself.

For comparison, see the (simplified) RESTAdapter:

```js
findAll(store, type, sinceToken, snapshotRecordArray) {
  let query = this.buildQuery(snapshotRecordArray);
  return this.ajax(url, 'GET', { data: query });
}
```

So this will work exactly the same as any other adapter.
