### ISSUE TITLE
Ember 2.13 support

### ISSUE THREAD

**Issue by tehmaestro** [mydea/ember-indexeddb#6]
Hi. Does this addon work with Ember 2.13? I cannot make it work, as `setup` function seems to be undefined.

**Comment by mydea** [comment]
Yes, it should definitely work for 2.13.
Have you set up the indexed-db-configuration service correctly, as described here: https://mydea.github.io/ember-indexeddb/docs/modules/Configuring%20your%20database.html?

Can you provide a code snippet where it fails?

**Comment by tehmaestro** [comment]
The service should be placed in `/services/indexed-db.js` right?

**Comment by mydea** [comment]
No, in `app/services/indexed-db-configuration.js`. You should usually not need to overwrite/extend the IndexedDb service itself.

**Comment by tehmaestro** [comment]
Ah, it works now, thank you.
