### ISSUE TITLE
.npmignore should include /.git/ to prevent npm install failing on error

### ISSUE THREAD

**Issue by CNovakPB** [mydea/ember-indexeddb#67]
After installing this repo using npm install, all future attempts to run npm install result in the following fatal error:

`npm ERR! git [path]/ember-indexeddb: Appears to be a git repo or submodule.`

Adding /.git/ to your .npmignore file should prevent this, based on these posts:

https://github.com/watadarkstar/react-native-typing-animation/issues/2
https://github.com/react-native-community/react-native-safe-area-view/pull/72
https://stackoverflow.com/questions/37857149/is-the-files-property-necessary-in-package-json

Since you include an .npmignore file, this issue must be resolved there, not .gitignore (which is being ignored in favor of .npmignore).

npm must be instructed to not include the .git folder when this repo is installed as a dependency, which is not happening currently.

I have a branch I could submit for review/merging, but your repo does not accept branches from strangers.

Please fix this ASAP. I would love to use this in a project at my job, but I cannot submit my changes to our repo if I know your addon is going to prevent npm install from ever running again!

**Comment by CNovakPB** [comment]
Verified the fix works via fork: https://github.com/CNovakPB/ember-indexeddb/commit/2859b0ff50e5a879879d9f8bf3221f4f3b8bd350

**Comment by mydea** [comment]
Thanks, could you make a PR with the change, then I'll happily merge it!
