### ISSUE TITLE
Consider dropping (unused?) jQuery

### ISSUE THREAD

**Issue by jacobq** [mydea/ember-indexeddb#8]
I haven't looked through other files yet, but I noticed that `jQuery` is imported here but apparently not used.
https://github.com/mydea/ember-indexeddb/blob/master/addon/adapters/indexed-db.js#L6

**Comment by mydea** [comment]
We use `$.extend()` right now to deep-clone options. But I guess this would be easy to refactor - I'll take a stab when I find some time. I would also accept a PR for that :)

**Comment by jacobq** [comment]
I wasn't even going that far -- just saying that you could remove it from `addon/adapters/indexed-db.js` without any other changes.

**Comment by jacobq** [comment]
:man_facepalming: You're right; I'm sorry. Scanning through with Ctrl+F I only saw the template usages.

**Comment by mydea** [comment]
No worries ;)

**Comment by jacobq** [comment]
FWIW, [`_.cloneDeep`](https://lodash.com/docs/4.17.10#cloneDeep) offers the same functionality (I believe) and can be brought in on its own.

**Comment by mydea** [comment]
BTW, I have since replaced this with a non-jQuery version, so this addon is now jQuery free.
